### ISSUE TITLE
Update Asciidoctor PDF backend of the user-guide

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1099]
## Overview

The PDF backend of the User Guide is disabled at the moment, since it does not work with Java 9.

See `documentation/documentation.gradle:83` for backend configuration.

See https://github.com/jruby/jruby/issues/4805 for the underlying issue.

## Related Issues

- #770 
- #777 

## Deliverables

- [ ] Fix broken links:
  - [ ] link from PDF version of User Guide to release notes
  - [ ] link from PDF version of Release Notes to user guide
- [ ] Enable PDF backend when https://github.com/jruby/jruby/issues/4805 is solved and JRuby **9.1.14** is released.

**Comment by marcphilipp** [comment]
jruby/jruby#4805 is solved but we'll have to wait for JRuby 9.1.14 to be released.

**Comment by sormuras** [comment]
Only 12% to go... https://github.com/jruby/jruby/milestone/66

**Comment by sormuras** [comment]
Reopended due to failing Jenkins build: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/100/pipeline

```
Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59)
	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
[...]
```

**Comment by sormuras** [comment]
- Same issue on Jenkins: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/issues%2F1099-pdf-user-guide/1/pipeline
On Windows the PDF is created. On Linux it still fails with the error listed above.

- Add `org.jruby:jruby-complete:9.1.15.0` to the `asciidoctor` dependencies: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/issues%2F1099-pdf-user-guide/3/pipeline
On Windows the PDF is created, no change on Linux:
```
Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1

	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)

	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)

	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
[...]
```

**Comment by sbrannen** [comment]
oh well... 😞

**Comment by sbrannen** [comment]
FYI: I added deliverables for the broken links

**Comment by sormuras** [comment]
The PDF backend breaks on Java 10... will disable it for now.

**Comment by sormuras** [comment]
Seems to run on Windows and MacOS using JDK 10 again. Linux OS tests are pending...
