### ISSUE TITLE
AssertAll#assertAll() should display stack trace of all failed assertions

### ISSUE THREAD

**Issue by kamkie** [junit-team/junit5#1602]
## Overview

Currently, on failure `Assertions.assertAll()` only shows the stack trace for the `assertAll()` method itself but not for lambda expressions that actually failed.

When there are multiple failures it is hard to know which one failed if the error message is this same (multiple `assertTrue()` or similar `assertEquals()`).

In contrast, soft assertions in AssertJ display all failed stack traces but do not support lambda expressions.

## Deliverables

- [ ] Add failures in `assertAll()` as _suppressed exceptions_ in Jupiter.
- [ ] Document enhancement in the Release Notes.

**Comment by kamkie** [comment]
``java
        Assertions.assertAll(
                () -> assertThat(false).isFalse(),
                () -> assertThat(true).isFalse(),
                () -> assertThat(true).isFalse()
        );
```
adding exception as suppressed is not making them visible
```
Expected :false
Actual   :true
 <Click to see difference>




Expected :false
Actual   :true
 <Click to see difference>



org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	expected:<[fals]e> but was:<[tru]e>
	expected:<[fals]e> but was:<[tru]e>

	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:43)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:37)
	at org.junit.jupiter.api.Assertions.assertAll(Assertions.java:1068)
	at com.example.component.PasswordEncoderTest.notExistingEncoder(PasswordEncoderTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by kamkie** [comment]
MultipleFailuresError is not using addSuppressed at all

**Comment by marcphilipp** [comment]
**Team Decision:** Add failures as suppressed exceptions in Jupiter.

**Comment by JLLeitschuh** [comment]
I've had complaints from multiple developers on my team about this part of Junit5.
I think at one point all of the stack traces were captured, but this is no longer happening.

**Comment by marcphilipp** [comment]
About which part? `assertAll`?

**Comment by JLLeitschuh** [comment]
Correct.

**Comment by sbrannen** [comment]
added _Deliverables_

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
FYI: with my upcoming commit, the following test passes...

```java
@Test
void assertAllWithExecutablesThatThrowAssertionErrors() {
	// @formatter:off
	MultipleFailuresError multipleFailuresError = assertThrows(MultipleFailuresError.class, () ->
		assertAll(
			() -> assertFalse(true),
			() -> assertFalse(true)
		)
	);
	// @formatter:on

	assertExpectedExceptionTypes(multipleFailuresError, AssertionFailedError.class, AssertionFailedError.class);

	multipleFailuresError.printStackTrace(System.err);
	assertEquals(2, multipleFailuresError.getSuppressed().length, "number of suppressed exceptions");
}
```

... and it prints the following:

```
org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	expected: <false> but was: <true>
	expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:80)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:44)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:38)
	at org.junit.jupiter.api.Assertions.assertAll(Assertions.java:2250)
	at org.junit.jupiter.api.AssertAllAssertionsTests.lambda$18(AssertAllAssertionsTests.java:104)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:54)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:36)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2361)
	at org.junit.jupiter.api.AssertAllAssertionsTests.assertAllWithExecutablesThatThrowAssertionErrors(AssertAllAssertionsTests.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:523)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:1)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$2(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$2(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$2(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$7(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
	Suppressed: org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
		at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
		at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:40)
		at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:35)
		at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:185)
		at org.junit.jupiter.api.AssertAllAssertionsTests.lambda$19(AssertAllAssertionsTests.java:105)
		at org.junit.jupiter.api.AssertAll.lambda$1(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 49 more
	Suppressed: org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
		at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
		at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:40)
		at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:35)
		at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:185)
		at org.junit.jupiter.api.AssertAllAssertionsTests.lambda$20(AssertAllAssertionsTests.java:106)
		at org.junit.jupiter.api.AssertAll.lambda$1(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 49 more
```

**Comment by sbrannen** [comment]
This has been addressed in `master` in fe7f525e1046c50ec0c9e07f215418b18f92b547.

**Comment by JLLeitschuh** [comment]
@sbrannen Any chance this could be backported to the `5.3` lineup? In its current state, it makes `assertAll` really hard to debug when there are failures.

**Comment by marcphilipp** [comment]
Not sure why we missed this one when composing the list of fixes to backport for 5.3.2. Probably because it isn't labeled as "bug". FWIW I think we should have included it. However, I don't think it warrants a release on its own. We intend to release 5.4 M1 soon and 5.4 shortly after, probably early next year.

**Comment by 91wzhang** [comment]
@marcphilipp It appears that this feature is still not working with Gradle (6). A quick investigation has shown that Gradle decides MultipleFailuresError is not serialisable and converts it into PlaceholderException where suppressed exceptions are dropped. AssertionError, however, will not be converted and suppressed exceptions are preserved. Maybe it's something for the Gradle team?

**Comment by marcphilipp** [comment]
@91wzhang Yes, that's why I opened https://github.com/gradle/gradle/issues/9487 a while ago.

**Comment by DidierLoiseau** [comment]
Am I right that this was not implemented for JUnit Vintage? (using version 5.6.3 but seems to be the case still today in [TestRun.java](https://github.com/junit-team/junit5/blob/main/junit-vintage-engine/src/main/java/org/junit/vintage/engine/execution/TestRun.java#L196))

**Comment by sbrannen** [comment]
@DidierLoiseau, it does appear that the same fix should be applied to JUnit Vintage.

Would you please [create a new issue](https://github.com/junit-team/junit5/issues/new/choose) so that we can address this in 5.8.
