### ISSUE TITLE
JUnit Jupiter is not executing pure junit5 test (--select-class option)

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5#2245]
Hey,

We have a huge database with junit4 tests and we want to start using junit5. 

I have configured an ant task that uses the junit console launcher directly. I am able to successfully run using the junit platform vintage engine a pure old-school junit4 test case, but I am not able to run any junit5 tests although I have listed both engines in the ant task:   

```xml        
<arg line="--include-engine=junit-jupiter"/>
<arg line="--include-engine=junit-vintage"/>
```

To eliminate the ant layer, I tried doing the same using command line only. Here is my command:

```shell
java -jar junit-platform-console-standalone-1.6.0-RC1.jar --disable-ansi-colors --details-theme=ascii --select-class=com.pcbsys.nirvana.nAdminAPI.JmxConnectionTest1 --classpath=C:\10.7.0.x\jars\nServer10.7.0.0.1.jar;C:\10.7.0.x\jars\nJUnitTests10.7.0.0.1.jar;C:\10.7.0.x\jars\integration-test-ext10.7.0.0.1.jar;C:\10.7.0.x\jars\nPlugin10.7.0.0.1.jar;C:\10.7.0.x\jars\nProtocols10.7.0.0.1.jar;C:\10.7.0.x\jars\nAdminAPI10.7.0.0.1.jar;C:\10.7.0.x\jars\nClient10.7.0.0.1.jar;C:\10.7.0.x\jars\nEnterpriseManager10.7.0.0.1.jar;C:\10.7.0.x\jars\nJMS10.7.0.0.1.jar;C:\10.7.0.x\jars\testServerFramework10.7.0.0.1.jar;C:\10.7.0.x\jars\umExtensions10.7.0.0.1.jar;C:\10.7.0.x\jars\umModules10.7.0.0.1.jar;C:\10.7.0.x\jars\umTools10.7.0.0.1.jar;C:\10.7.0.x\jars\umSampleApplications10.7.0.0.1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-console-standalone-1.6.0-RC1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-engine-1.6.0-RC1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-launcher-1.6.0-RC1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-runner-1.6.0-RC1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-commons-1.6.0-RC1.jar;C:\10.7.0.x\build\nirvana-dependencies\junit5\junit-platform-suite-api-1.6.0-RC1.jar
```

The test class `com.pcbsys.nirvana.nAdminAPI.JmxConnectionTest1` uses only junit 5 and lives in `C:\10.7.0.x\jars\nJUnitTests10.7.0.0.1.jar`.

The output I get is: 

```
Thanks for using JUnit! Support its development at https://junit.org/sponsoring

.
+-- JUnit Jupiter [OK]
'-- JUnit Vintage [OK]

Test run finished after 24 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

The test is not executed although it seems to be detected somehow (I do not know how to interpret the output - my test has 3 methods while it says 2 containers detected)

The same command works perfectly well when I supply another test class that uses junit4 only – obviously picked up by the vintage execution.

What am I doing wrong?

**Comment by Vazzilena** [comment]
[ant_full_output.txt](https://github.com/junit-team/junit5/files/4440252/ant_full_output.txt)

[JmxConnectionTest1.java.txt](https://github.com/junit-team/junit5/files/4440267/JmxConnectionTest1.java.txt)

**Comment by sbrannen** [comment]
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by sbrannen** [comment]
> The test is not executed although it seems to be detected somehow (I do not know how to interpret the output - my test has 3 methods while it says 2 containers detected)

Actually, it appears that you Jupiter test class is not detected.

The 2 containers are for the Jupiter and Vintage engines.

Regarding Ant and JUnit 5, why do you not use the dedicated [`junitlauncher`](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-ant) task?

**Comment by Vazzilena** [comment]
We prefer using the launcher directly - more configuration options and easier to reproduce problems using the command line. 

It should be working both ways I guess (ant and/or pure command line launcher).

Why is not picking up my test? 

(Thanks for editing my initial post - I will read the markdown guide :) )

**Comment by Vazzilena** [comment]
> > The test is not executed although it seems to be detected somehow (I do not know how to interpret the output - my test has 3 methods while it says 2 containers detected)
> 
> Actually, it appears that your Jupiter test class is not detected.
> 
> The 2 containers are for the Jupiter and Vintage engines.
> 
> Regarding Ant and JUnit 5, why do you not use the dedicated [`junitlauncher`](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-ant) task?

I prefer using the console launcher directly because it provides more configuration options, which we can mix. And it is also easier to reproduce problems using a command line. 
I might consider adopting the ant task as well, once I get it properly running. 

Why is it not picking up my test?

**Comment by Vazzilena** [comment]
> I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

Thanks! I will read it.

**Comment by sbrannen** [comment]
Note that `JmxConnectionTest1` does not end it `Test` but rather in `Test1`.

Have you tried setting the `--include-classname` option to a pattern that includes test class names that have `Test` in the middle of the class name?

**Comment by Vazzilena** [comment]
> Note that `JmxConnectionTest1` does not end it `Test` but rather in `Test1`.
> 
> Have you tried setting the `--include-classname` option to a pattern that includes test class names that have `Test` in the middle of the class name?

Yes, it ends up with Test1, but this is exactly what I am supplying in my command line arguments.

I have not tried the option you mention, but it would not cover my use case as I want to run a single test...

**Comment by sbrannen** [comment]
> I have not tried the option you mention, but it would not cover my use case as I want to run a single test...

Are you sure about that?

https://github.com/junit-team/junit5/blob/78c989fe2c4fe1c8d741921c12dfcd2bff504882/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java#L178-L179

**Comment by Vazzilena** [comment]
> > I have not tried the option you mention, but it would not cover my use case as I want to run a single test...
> 
> Are you sure about that?
> 
> https://github.com/junit-team/junit5/blob/78c989fe2c4fe1c8d741921c12dfcd2bff504882/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java#L178-L179

Hey Sam,

What are you suggesting – that I stop using [--select-class] option and replace it with [--include-classname] option? 

Would this be a valid pattern - ^com.pcbsys.nirvana.nAdminAPI.JmxConnectionTest1$ to isolate only the test case in question?

And would it work with vintage engine (because [--select-class] works well with vitage) and I want to use the same options for both engines...

**Comment by sbrannen** [comment]
What I'm saying is ...

1. I believe the default class name filter is always applied. In the code it seems to definitely be the case, but I have not thrown together an example to prove it. I'll leave that to you to try out.
2. If the default filter is always applied and your test classes don't match the default pattern, you simply have to override the default pattern with a pattern that matches against your naming conventions (or simply match against anything with a wildcard pattern).

> And would it work with vintage engine (because [--select-class] works well with vitage) and I want to use the same options for both engines...

Do the tests you execute via the Vintage engine perhaps use different naming conventions? If so, that might explain the different behavior you're experiencing.

**Comment by marcphilipp** [comment]
The `ConsoleLauncher` uses the `STANDARD_INCLUDE_PATTERN` that will be applied to all classes regardless if they are passed via `--select-class` or some other means. Since your test name does not match the `^(Test.*|.+[.$]Test.*|.*Tests?)$` regex it will be excluded. Please either rename your test class or pass a different regex (e.g. `.*`).

**Comment by Vazzilena** [comment]
Thanks for the help guys - keeping the same arguments but adding --include-class name=<TEST_CLASS> to override the default pattern solved my problem.

Adding the digit 1 to the name of the test was just an experiment, but sill valuable as many of our tests do not follow this convention, so I would have run into the same problem anyway...

**Comment by Vazzilena** [comment]
Guys,
Apologies for writing in the same issue but since my last question turned out to be configuration issue, I decided it is better to ask. Running with platform console launcher arguments: 
--include-tag=new 

I am getting the output bellow (stack trace listed in between in output)

### [jacoco:coverage] Enhancing java with coverage
     [java]
     [java] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
     [java]
     [java] Usage: ConsoleLauncher [-h] [--disable-ansi-colors] [--disable-banner]
     [java]                        [--fail-if-no-tests] [--scan-modules] [--scan-classpath[=PATH[;|:
     [java]                        PATH...]]]... [--details=MODE] [--details-theme=THEME]
     [java]                        [--reports-dir=DIR] [-c=CLASS]... [--config=KEY=VALUE]... [-cp=PATH
     [java]                        [;|:PATH...]]... [-d=DIR]... [-e=ID]... [-E=ID]...
     [java]                        [--exclude-package=PKG]... [-f=FILE]... [--include-package=PKG]...
     [java]                        [-m=NAME]... [-n=PATTERN]... [-N=PATTERN]... [-o=NAME]...
     [java]                        [-p=PKG]... [-r=RESOURCE]... [-t=TAG]... [-T=TAG]... [-u=URI]...
     [java] Launches the JUnit Platform from the console.
     [java]   -h, --help                 Display help information.
     [java]       --disable-ansi-colors  Disable ANSI colors in output (not supported by all
     [java]                                terminals).
     [java]       --disable-banner       Disable print out of the welcome message.
     [java]       --details=MODE         Select an output details mode for when tests are executed.
     [java]                                Use one of: none, summary, flat, tree, verbose. If 'none'
     [java]                                is selected, then only the summary and test failures are
     [java]                                shown. Default: tree.
     [java]       --details-theme=THEME  Select an output details tree theme for when tests are
     [java]                                executed. Use one of: ascii, unicode. Default: ascii.
     [java]       -cp, --classpath, --class-path=PATH[;|:PATH...]
     [java]                              Provide additional classpath entries -- for example, for
     [java]                                adding engines and their dependencies. This option can be
     [java]                                repeated.
     [java]       --fail-if-no-tests     Fail and return exit status code 2 if no tests are found.
     [java]       --reports-dir=DIR      Enable report output into a specified local directory (will
     [java]                                be created if it does not exist).
     [java]       --scan-modules         EXPERIMENTAL: Scan all resolved modules for test discovery.
     [java]   -o, --select-module=NAME   EXPERIMENTAL: Select single module for test discovery. This
     [java]                                option can be repeated.
     [java]       --scan-classpath, --scan-class-path[=PATH[;|:PATH...]]
     [java]                              Scan all directories on the classpath or explicit classpath
     [java]                                roots. Without arguments, only directories on the system
     [java]                                classpath as well as additional classpath entries supplied
     [java]                                via -cp (directories and JAR files) are scanned. Explicit
     [java]                                classpath roots that are not on the classpath will be
     [java]                                silently ignored. This option can be repeated.
     [java]   -u, --select-uri=URI       Select a URI for test discovery. This option can be repeated.
     [java]   -f, --select-file=FILE     Select a file for test discovery. This option can be
     [java]                                repeated.
     [java]   -d, --select-directory=DIR Select a directory for test discovery. This option can be
     [java]                                repeated.
     [java]   -p, --select-package=PKG   Select a package for test discovery. This option can be
     [java]                                repeated.
     [java]   -c, --select-class=CLASS   Select a class for test discovery. This option can be
     [java]                                repeated.
     [java]   -m, --select-method=NAME   Select a method for test discovery. This option can be
     [java]                                repeated.
     [java]   -r, --select-resource=RESOURCE
     [java]                              Select a classpath resource for test discovery. This option
     [java]                                can be repeated.
     [java]   -n, --include-classname=PATTERN
     [java]                              Provide a regular expression to include only classes whose
     [java]                                fully qualified names match. To avoid loading classes
     [java]                                unnecessarily, the default pattern only includes class
     [java]                                names that begin with "Test" or end with "Test" ororg.junit.platform.commons.PreconditionViolationException: No arguments were supplied to the ConsoleLauncher
     [java]                                "Tests". When this option is repeated, all patterns will
     [java]                                be combined using OR semantics. Default: [^(Test.*|.+[.$]
     [java]                                Test.*|.*Tests?)$]
     [java]     at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:281)
     [java]     at org.junit.platform.commons.util.Preconditions.notEmpty(Preconditions.java:126)
     [java]     at org.junit.platform.console.tasks.DiscoveryRequestCreator.createExplicitDiscoverySelectors(DiscoveryRequestCreator.java:93)
     [java]   -N, --exclude-classname=PATTERN
     [java]     at org.junit.platform.console.tasks.DiscoveryRequestCreator.createDiscoverySelectors(DiscoveryRequestCreator.java:65)
     [java]
     [java]     at org.junit.platform.console.tasks.DiscoveryRequestCreator.toDiscoveryRequest(DiscoveryRequestCreator.java:48)
     [java]     at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
     [java]     at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
     [java]                              Provide a regular expression to exclude those classes whose
     [java]                                fully qualified names match. When this option is repeated,
     [java]                                all patterns will be combined using OR semantics.
     [java]       --include-package=PKG  Provide a package to be included in the test run. This
     [java]                                option can be repeated.      at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.replaceThreadContextClassLoaderAndInvoke(CustomContextClassLoaderExecutor.java:41)
     [java]
     [java]       --exclude-package=PKG  Provide a package to be excluded from the test run. This
     [java]                                option can be repeated.
     [java]   -t, --include-tag=TAG      Provide a tag or tag expression to include only tests whose
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]     at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:31)  -T, --exclude-tag=TAG      Provide a tag or tag expression to exclude those tests whose
     [java]     at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
     [java]     at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
     [java]     at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
     [java]     at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
     [java]     at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
     [java]
     [java]     at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
     [java]
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]   -e, --include-engine=ID    Provide the ID of an engine to be included in the test run.
     [java]                                This option can be repeated.
     [java]   -E, --exclude-engine=ID    Provide the ID of an engine to be excluded from the test
     [java]                                run. This option can be repeated.
     [java]       --config=KEY=VALUE     Set a configuration parameter for test discovery and
     [java]                                execution. This option can be repeated.

**Comment by marcphilipp** [comment]
The garbled output probably comes from your output handling since the stacktrace is written to System.err and the help text to System.out.

The cause of the exception is that you haven't specified any selectors. `--include-tag=new` is not a selector but a filter. If you want to run all tagged tests on the classpath, please supply `--scan-classpath` as well.

**Comment by Vazzilena** [comment]
Many thanks for taking the time to reply.

I corrected my arguments to: 

### --include-tag=new --scan-classpath=C:\junit-5/jars/nJUnitTests10.7.0.0.1.jar

(nJUnitTests10.7.0.0.1.jar is the jar that contains all the tests - bith junit4 and a single junit5 test).

It seems to be picking ALL tests now regardless where or not they use the @Tag annotation.

I was execting that it would pick that single junit5 test which is the only one that has the @Tag annnotation... what am I doing wrong this time?

**Comment by marcphilipp** [comment]
That's weird. I cannot reproduce this on my end. Please provide a minimal reproducer and open a new issue so we can investigate.

**Comment by Vazzilena** [comment]
Okay, so what fixed it for me was adding 
`--include-engine=junit-jupiter --include-tag=@{tag} --include-classname=.* --scan-classpath=@{scan.classpath}`


Initially, when it was picking up everting I had both vitage and jupiter engines turned on. 

I still do not understand why it would pick up all vitage test cases if I am supplying explicitly the tag option – maybe arguments have some precedence that I do not know…

I think I got it working - THANK YOU :)

**Comment by bennetelli** [comment]
I'm experiencing the same issue as described above. Tried several things like moving the jar around, trying lots of parameters, but it's still not working. The standalone console doesn't find Tests.

**Comment by sormuras** [comment]
@bennetelli ... a bit more information about your case would help us to help you. 😉

**Comment by bennetelli** [comment]
haha, sorry.. you are right ;-)

I've got a plain Gradle project, build the application and wanted to run the compiled junit jupiter tests by using the standalone-console.
